In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.5.2

Please update conda by running

    $ conda update -n base -c defaults conda




In [2]:
import numpy as np

# NUMPY

In [3]:
print("Mars")

Mars


In [4]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b = np.array([[10,20,30,45],[40,50,60,78],[36,45,68,89]])
print(b)

[[10 20 30 45]
 [40 50 60 78]
 [36 45 68 89]]


In [6]:
c = np.zeros(4)
print(c)

[0. 0. 0. 0.]


In [7]:
d=np.arange(54,59)
print(d)

[54 55 56 57 58]


In [8]:
print(np.linspace(1,50,num=4,dtype=np.int64))

[ 1 17 33 50]


In [9]:
print(np.ones(5,dtype=np.int64))

[1 1 1 1 1]


In [10]:
print(np.shape(d))

(5,)


In [11]:
print(np.ndim(b))

2


In [12]:
print(np.shape(b))
print(np.size(b))

(3, 4)
12


In [13]:
n=np.concatenate((a,d))
print(n)

[ 1  2  3  4  5 54 55 56 57 58]


n[:3]

In [14]:
print(n[n>50])

[54 55 56 57 58]


# Pandas


In [15]:
conda install pandas

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.5.2

Please update conda by running

    $ conda update -n base -c defaults conda




In [16]:
import pandas as pd

In [17]:
a=pd.Series([18,23,39,48,51])
a

0    18
1    23
2    39
3    48
4    51
dtype: int64

In [18]:
df=pd.DataFrame(np.random.randn(2,3),dtype=np.int32)
df

0  1  2
0  1 -1  0
1  0  0  1

In [19]:
df1=pd.DataFrame(
{
   "Nivash":1.0,
    "Harish":np.arange(5),
    "Santhosh":pd.Series(np.nan,index=list(range(5))),
})
df1

Nivash  Harish  Santhosh
0     1.0       0       NaN
1     1.0       1       NaN
2     1.0       2       NaN
3     1.0       3       NaN
4     1.0       4       NaN

In [20]:
df1.index

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [21]:
df1.columns

Index(['Nivash', 'Harish', 'Santhosh'], dtype='object')

In [22]:
df1.describe()

Nivash    Harish  Santhosh
count     5.0  5.000000       0.0
mean      1.0  2.000000       NaN
std       0.0  1.581139       NaN
min       1.0  0.000000       NaN
25%       1.0  1.000000       NaN
50%       1.0  2.000000       NaN
75%       1.0  3.000000       NaN
max       1.0  4.000000       NaN

In [23]:
df1[0:3]

Nivash  Harish  Santhosh
0     1.0       0       NaN
1     1.0       1       NaN
2     1.0       2       NaN

In [24]:
df1["Harish"]

0    0
1    1
2    2
3    3
4    4
Name: Harish, dtype: int32

In [25]:
df1.loc[0:2]

Nivash  Harish  Santhosh
0     1.0       0       NaN
1     1.0       1       NaN
2     1.0       2       NaN

In [26]:
df1.iloc[0:2]

Nivash  Harish  Santhosh
0     1.0       0       NaN
1     1.0       1       NaN

In [27]:
df1.loc["Nivash":"Harish"]

Empty DataFrame
Columns: [Nivash, Harish, Santhosh]
Index: []

In [28]:
df1[df1["Nivash"]<=3]

Nivash  Harish  Santhosh
0     1.0       0       NaN
1     1.0       1       NaN
2     1.0       2       NaN
3     1.0       3       NaN
4     1.0       4       NaN

In [29]:
pd.isna(df1)

Nivash  Harish  Santhosh
0   False   False      True
1   False   False      True
2   False   False      True
3   False   False      True
4   False   False      True

In [30]:
np.isnan(df1)

Nivash  Harish  Santhosh
0   False   False      True
1   False   False      True
2   False   False      True
3   False   False      True
4   False   False      True

In [31]:
df1.dropna()

Empty DataFrame
Columns: [Nivash, Harish, Santhosh]
Index: []